version: '2'
services:
  dev:
    build:
      context: .
      dockerfile: dev/Dockerfile
    volumes:
      - mysqlapp-volume:/opt/myapp/App42PaaS-Java-MySQL-Sample/target/
    depends_on:
      - db

  prod:
    build:
      context: .
      dockerfile: prod/Dockerfile
    depends_on:
      - dev
    ports:
      - "8080:8080"
    volumes:
      - mysqlapp-volume:/opt/tomcat/webapps/
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webapp
      MYSQL_USER: userapp
      MYSQL_PASSWORD: pass
    command: '--default-authentication-plugin=mysql_native_password'

volumes:
  mysqlapp-volume: {}

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
