version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: dev/Dockerfile
    volumes:
      - mysqlapp-volume:/opt/myapp/App42PaaS-Java-MySQL-Sample/target/

  prod:
    build:
      context: .
      dockerfile: prod/Dockerfile
    depends_on:
      - dev
      - db
    ports:
      - "8080:8080"
    networks:
      - mysql_net
    volumes:
      - mysqlapp-volume:/opt/tomcat/webapps/

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - mysql_net
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webapp
      MYSQL_USER: userapp
      MYSQL_PASSWORD: pass
    command: '--default-authentication-plugin=mysql_native_password'

volumes:
  mysqlapp-volume: {}

networks:
  mysql_net:
    driver: bridge
