pipeline {
  agent {

    docker {
      image '172.17.0.1:5000/docker-agent:latest'
            args '-u root:sudo --privileged -v /var/run/docker.sock:/var/run/docker.sock'
            }
         }
  stages {

    stage('Copy source') {
      steps {
        git 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      }
    }

    stage('Build war') {
      steps {
        sh 'mvn package'
      }
    }

    stage('Make docker image') {
      steps {
        sh 'cp ./target/hello-1.0.war /root/docker/hello-1.0.war && cd /root/docker/ && docker build --tag=prodserv .'
        sh 'cd /root/docker/ && cat my_password.txt | docker login --username admin --password-stdin 172.17.0.1:5000'
        sh 'docker tag prodserv 172.17.0.1:5000/prodserv && docker push 172.17.0.1:5000/prodserv'
      }
    }

    stage('Run docker prodserver') {
      steps {
        sh 'docker pull 172.17.0.1:5000/prodserv && docker run -d -p 8081:8081 prodserv '
      }
    }
  }
}

