---
# tasks file for dev
    - name: Ensure Dev-apps are present
      apt:
        pkg:
          - openjdk-11*
          - git
        update_cache: yes
        state: latest
    - name: Is artifact exists
      stat:
        path: /opt/myapp/target/Puzzle15-1.0-SNAPSHOT.war
      register: app_war
    - name: git clone java app
      git:
        repo: https://github.com/venkaDaria/puzzle15.git
        dest: /opt/myapp
      when: not app_war.stat.exists
    - name: change pom.xml
      lineinfile:
        path: /opt/myapp/pom.xml
        regexp: '^</project>'
        line: <properties><maven.compiler.source>1.8</maven.compiler.source><maven.compiler.target>1.8</maven.compiler.target></properties></project>
      when: not app_war.stat.exists
    - name: build app
      command: "mvn war:war"
      args:
        chdir: "/opt/myapp/"
      #when: not app_war.stat.exists
    - name: Pull war artifact
      fetch:
        src: /opt/myapp/target/Puzzle15-1.0-SNAPSHOT.war
        dest: /opt