FROM alpine:latest

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN  apk -U upgrade --update && \
        apk --no-cache add openjdk11 && \
        apk --no-cache add maven && \
        apk --no-cache add git && \
        apk --no-cache add bash

ENTRYPOINT ["/bin/sh", "-c", "/bin/bash"]