---
- name: Set TimeZone
  hosts: all
  become: yes
  tasks:
    - name: Set TimeZone cmd
      shell:
        cmd: >
         if grep  -v 'Moscow' /etc/timezone;
         then ln -snf /usr/share/zoneinfo/Europe/Moscow /etc/localtime &&
         echo "Europe/Moscow" > /etc/timezone; fi

- name: install dev enviroment
  hosts: dev
  become: yes
  tasks:
    - name: Ensure Dev-app are present
      apt:
        pkg:
          - default-jdk
          - maven
          - git
        update_cache: yes
        state: latest


 #       name: nginx
  #      state: present
    - name: Ensure index.html is present
      copy:
        src: index.html
        dest: /var/www/html
    - name: Ensure nginx service is started
      service:
        name: nginx
        state: started

- name: install db
  hosts: db
  become: yes


  tasks:
    - name: Ensure postgresql is present
      apt:
        name: postgresql
        state: present
    - name: Ensure postegresql service started
      service:
        name: postgresql
        state: started
