---
- name: Set TimeZone
  hosts: all
  become: yes
  tasks:
    - name: Set timezone variables
      copy:
        src: /etc/timezone
        dest: /etc/timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

- name: install Dev enviroment
  hosts: dev
  become: yes
  tasks:
    - name: Ensure Dev-app are present
      apt:
        pkg:
          - default-jdk
          - maven
          - git
        update_cache: yes
        state: latest

- name: install Prod enviroment
  hosts: prod
  become: yes
  tasks:
    - name: Ensure Prod-app are present
      apt:
        pkg:
          - tomcat9
          - git
        update_cache: yes
        state: latest
    - name: Ensure tomcat are started
      service:
        name: tomcat9
        state: started
  tags:
   - tomcat9


