---
- name: Set TimeZone
  hosts: all
  become: yes
  tasks:
    - name: Set timezone variables
      copy:
        src: /etc/timezone
        dest: /etc/timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

- name: install Dev enviroment
  hosts: dev
  become: yes
  tasks:
    - name: Ensure Dev-app are present
      apt:
        pkg:
          - default-jdk
          - maven
          - git
        update_cache: yes
        state: latest
    - name: Get and make test java app
      shell: >
        mkdir -p /opt/myapp && cd /opt/myapp && \
        git clone https://github.com/venkaDaria/puzzle15.git && \
        cd ./puzzle15 && \
        sed  -i 's/<\/project>/<properties><maven.compiler.source>1.8<\/maven.compiler.source><maven.compiler.target>1.8<\/maven.compiler.target><\/properties><\/project>/' pom.xml && \
        mvn package
    - name: Pull war artifact
      fetch:
       src: /opt/myapp/puzzle15/target/Puzzle15-1.0-SNAPSHOT.war
       dest: /opt

- name: install Prod enviroment
  hosts: prod
  become: yes
  tasks:
    - name: Ensure Prod-app are present
      apt:
        pkg:
          - tomcat9
          - git
        update_cache: yes
        state: latest
    - name: Ensure tomcat are started
      service:
        name: tomcat9
        state: started
    - name: Push war artifact
      ## Two methods below need to set up public key authentication
      ## [dev]#35.228.242.166  ##[prod]#35.228.97.111
      #synchronize:
      #  mode: push
      #  src: /opt/myapp/puzzle15/target/Puzzle15-1.0-SNAPSHOT.war
      #  dest: /var/lib/tomcat9/webapps/Puzzle15-1.0-SNAPSHOT.war
      #delegate_to: 35.228.242.166
      #################################################################
      ## this one is the shortest
      #shell: scp root@35.228.242.166:/opt/myapp/puzzle15/target/Puzzle15-1.0-SNAPSHOT.war /var/lib/tomcat9/webapps/
      copy:
        src: /opt/35.228.242.166/opt/myapp/puzzle15/target/Puzzle15-1.0-SNAPSHOT.war
        dest: /var/lib/tomcat9/webapps




