---
- name: Set TimeZone
  hosts: all
  become: yes
  tasks:
    - name: Set timezone variables
      copy:
        src: /etc/timezone
        dest: /etc/timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata




- name: install dev enviroment
  hosts: dev
  become: yes
  tasks:
    - name: Ensure Dev-app are present
      apt:
        pkg:
          - default-jdk
          - maven
          - git
        update_cache: yes
        state: latest


 #       name: nginx
  #      state: present
    - name: Ensure index.html is present
      copy:
        src: index.html
        dest: /var/www/html
    - name: Ensure nginx service is started
      service:
        name: nginx
        state: started

- name: install db
  hosts: db
  become: yes


  tasks:
    - name: Ensure postgresql is present
      apt:
        name: postgresql
        state: present
    - name: Ensure postegresql service started
      service:
        name: postgresql
        state: started
