#!/bin/bash

function mvn_package
    {
            if [ -d "$dest" ]; then
                        cd $dest
                        changed="true"
                        msg="change dir"
                        output=$(mvn package 2>&1 | python -c 'import json,sys; print json.dumps(sys.stdin.read())')
                        if [ $? -ne 0 ]; then
                                printf '{"failed": true, "msg": "error mvn package", "output": %s}' "$output"
                        exit 1
            fi
       else
                changed="false"
                msg="directory does not exists"
                contents='""'
       fi
  }

source $1
 if [ -z "$dest" ]; then
     printf '{"failed": true, "msg": "missing required arguments: dest"}'
     exit 1
 fi
 if [ -z "$phase" ]; then
     printf '{"failed": true, "msg": "missing required arguments: phase"}'
     exit 1
 fi

changed="false"
msg=""
contents=""

case $phase in
    package)
        mvn_package
        ;;
    *)
        printf '{"failed": true, "msg": "invalid phase: %s"}' "$phase"
